### ISSUE TITLE
Accessing web interface remotely redirects to 127.0.0.1

### ISSUE THREAD

**Issue by GedRap** [martinrusev/amonone#149]
Hi,

I installed following the instructions from http://martinrusev.github.io/amonone/

However, I can't access it remotely although I have changed server name in the /etc/amonone.conf. I tried using both domain name and public IP address. When I try to open it remotely, it redirects me to http://127.0.0.1:2464/login?next=(replaced_IP_address).

I tried to open it using links browser from the server (i.e. locally), it asks me create a user and then shows login prompt but I can't log in.

I checked the log file, it's empty. I am trying to run it on EC2's Ubuntu, Python 2.7.3.

Thanks!

**Comment by jackbit** [comment]
edit your /etc/amonone.conf and change 127.0.0.1 with your public ip or domain and also the port, then restart your /etc/init.d/amonone and /etc/init.d/amonone-collector
